services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - agent-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d businessdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: text_to_sql_api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - agent-net
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - agent-net
    depends_on:
      db:
        condition: service_healthy

networks:
  agent-net:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: